### ISSUE TITLE
Custom class adaptation

### ISSUE THREAD

**Issue by fryegg** [google/prompt-to-prompt#10]
Thanks for your research :) 
I wonder that this robust image editing method by attention injection can be adapted to custom class like Dreambooth research.
Ex) Photo of a cat riding a bicycle -> [V] car : give some custom class information like same car model images.

**Comment by Mohyuddin** [comment]
Thanks for your research :)

**Comment by amirhertz** [comment]
Probably you can combine  _Dreambooth_ / _Textual Inversion_ with our method but we haven't tested it.
