### ISSUE TITLE
Notebook links under Quickstart section produce 404's

### ISSUE THREAD

**Issue by meefs** [google/prompt-to-prompt#16]
Greets,

The links under the Quickstart section for [prompt-to-prompt_ldm](https://github.com/google/prompt-to-prompt/blob/main/%22./prompt-to-prompt_ldm.ipynb%22) and [prompt-to-prompt_stable](https://github.com/google/prompt-to-prompt/blob/main/%22./prompt-to-prompt_stable.ipynb%22) are broken. Below are the links for each notebook

prompt-to-prompt_ldm
https://github.com/google/prompt-to-prompt/blob/main/%22./prompt-to-prompt_ldm.ipynb%22

prompt-to-prompt_stable
https://github.com/google/prompt-to-prompt/blob/main/%22./prompt-to-prompt_stable.ipynb%22

Thanks,
meefs

**Comment by amirhertz** [comment]
Thanks, it was fixed.
