### ISSUE TITLE
Image Size in Null-Text Inversion

### ISSUE THREAD

**Issue by zhihongp** [google/prompt-to-prompt#33]
I am testing the inversion accuracy using COCO dataset but the result is not stable.  Only change I did is relaxing the hard-coded 512x512 image size.  Do you see any potential risks with that size change?  Thanks

**Comment by zhihongp** [comment]
Precision setting issue on my side, solved.

**Comment by ebartrum** [comment]
Hi @zhihongp, I also have an issue when changing the hardcoded image size, could you explain how you resolved it? Thank you!

**Comment by zhihongp** [comment]
I could not access the code right now to double check but I remember you need double-precision to learn the null-text embedding properly.
