### ISSUE TITLE
To those who have issues adapting it with Diffuersers version>=11.0

### ISSUE THREAD

**Issue by jacobswan1** [google/prompt-to-prompt#37]
You might be encoutering error about: 
`            hidden_states = self.attn1(norm_hidden_states, attention_mask=attention_mask) + hidden_states
`

Just simply rename argument attention_mask to mask, for self.attn2, rename encoder_hidden_states to context will fix the issue. 

It is because the register_attention_control function have different argument names with new version of diffusers.

**Comment by eps696** [comment]
hello, could you explain this issue a bit more? 
i believe i have run into it in some "updated" form, getting the error `forward() got an unexpected keyword argument 'encoder_hidden_states'` when running `register_attention_control` on null-inversion - yet i don't quite catch what and where should be changed to avoid that. do you mean changing the original diffusers code?

**Comment by eps696** [comment]
ok fixed my case by reversing the advice - renamed the stuff in `register_attention_control` function.
`context` => `encoder_hidden_states`, `mask` => `attention_mask`, `CrossAttention` => `AttentionBlock`

**Comment by liangbingzhao** [comment]
@eps696  I followed your advice, but found if change `CrossAttention` to `AttentionBlock`, the attention_store would be none. So in my case, I renamed `context` and `mask`, and stay with `CrossAttention`.

**Comment by bonlime** [comment]
On latest 0.13.1 diffusers version I had to:
rename `context` => `encoder_hidden_states`, `mask` => `attention_mask`,  `self.reshape_heads_to_batch_dim` -> `self.head_to_batch_dim`, `self.reshape_batch_dim_to_heads` -> `self.batch_to_head_dim` in `register_attention_control` and it started working correctly

**Comment by eps696** [comment]
@liangbingzhao @bonlime you are definitely right, i didn't notice that changing the block effectively disabled main workflow. yet the `CrossAttention` refactoring after 0.11.1 was quite gross, so i'm afraid more issues might appear

**Comment by moonnnpie** [comment]
i also use 0.13.1 diffusers version but got a problem

TypeError: PNDMScheduler.set_timesteps() got an unexpected keyword argument 'offset'

how should i fix it

**Comment by liangbingzhao** [comment]
@moonnnpie in the `ptp_util.py`, omit `extra_set_kwargs = {"offset": 1}`, and change `model.scheduler.set_timesteps(num_inference_steps, **extra_set_kwargs)` to `model.scheduler.set_timesteps(num_inference_steps)`. This error is because in the previous diffusers, scheduler's `set_timesteps` function has a param `offset`.

**Comment by moonnnpie** [comment]
> 

thanks a lot

**Comment by moonnnpie** [comment]
@liangbingzhao thanks a lot

**Comment by JiauZhang** [comment]
Hi, all, I have tried to port to diffusers==0.14.0, there is no runing error, but the result is actually bad...
https://github.com/JiauZhang/prompt-to-prompt   for now, I just simple replace attention map.
Could anyone give me some advice？

**Comment by pikeyang** [comment]
> Hi, all, I have tried to port to diffusers==0.14.0, there is no runing error, but the result is actually bad... https://github.com/JiauZhang/prompt-to-prompt for now, I just simple replace attention map. Could anyone give me some advice？

Is it solved?

**Comment by tian-2024** [comment]
> extra_set_kwargs

it's a great advice!!!!

**Comment by x2x5** [comment]
> @moonnnpie in the `ptp_util.py`, omit `extra_set_kwargs = {"offset": 1}`, and change `model.scheduler.set_timesteps(num_inference_steps, **extra_set_kwargs)` to `model.scheduler.set_timesteps(num_inference_steps)`. This error is because in the previous diffusers, scheduler's `set_timesteps` function has a param `offset`.

it's a great advice!!!!
