### ISSUE TITLE
too may indices for tensor of dimension 4

### ISSUE THREAD

**Issue by night3759** [google/prompt-to-prompt#5]
When I run this code, an error occurred in the function of latent2image. 

image = car.decode(latents)[“samples”]

too may indices for tensor of dimension 4

**Comment by AllanGaines** [comment]
Soy un novato aquí. Acabo de registrarme hace unos minutos. Ni siquiera sé mucho sobre estos temas. Pero me gustaría aprender y educarme.

**Comment by night3759** [comment]
This problem has benn solved. I downloaded the wrong version of diffusers of 0.24, which should be 0.3.
