### ISSUE TITLE
"TypeError: 'NoneType' object is not callable" upon model.unet() call 

### ISSUE THREAD

**Issue by josejhlee** [google/prompt-to-prompt#59]
Im running with diffusers 0.14.0
the "NoneType" call error is from the attention function in the forward pass of CrossAttnDownBlock2D

**Comment by g-jing** [comment]
I also got that problem. Do you have any solution for that?

**Comment by lxycopper** [comment]
same question, may I know how you fix it?

**Comment by josejhlee** [comment]
> same question, may I know how you fix it?

Cant remember exactly but try to check on the tab indent of the forward function in the utils.
