### ISSUE TITLE
Is LocalBlend an implementation of the mask-based real image editing technique described in the paper?

### ISSUE THREAD

**Issue by RyanCaesarRamos** [google/prompt-to-prompt#6]
Hi, just want to confirm if I'm correct in understanding that the `LocalBlend` object used in the "Local Edit" section of the `prompt-to-prompt_stable` notebook implements the technique in described in page 10 of the paper (i.e. the mask-based real image editing technique that does not rely on deterministic image inversion).

**Comment by amirhertz** [comment]
No, the LocalBlent is the implementation of the _Local Editing_ option, descrbied in our [revised version](https://prompt-to-prompt.github.io/ptp_files/Prompt-to-Prompt_preprint.pdf) (page 5).

**Comment by RyanCaesarRamos** [comment]
Thanks! Just to be clear, this repo doesn't have any implementations for the real image editing experiments described in the paper?

**Comment by amirhertz** [comment]
Yes, correct. We are working on a more robust version that will allow editing of real images.

**Comment by RyanCaesarRamos** [comment]
Thanks! Just want to say I really enjoyed your paper
